name: batch_workflow

on:
  workflow_dispatch:
  pull_request:
    path:
      - "batch_workflow/**.go"
      - "batch_workflow/**/go.mod"
      - "batch_workflow/**/go.sum"
      - ".github/workflows/batch_workflow.yml"
  push:
    branches:
      - master
    paths:
      - "batch_workflow/**.go"
      - "batch_workflow/**/go.mod"
      - "batch_workflow/**/go.sum"
      - ".github/workflows/batch_workflow.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: batch_workflow/go.mod
          cache: true
          cache-dependency-path: batch_workflow/go.sum
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: batch_workflow
          skip-pkg-cache: true
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: batch_workflow/go.mod
          cache: true
          cache-dependency-path: batch_workflow/go.sum
      - name: go tests
        run: go test ./...
        working-directory: ./batch_workflow
