name: go

on:
  workflow_dispatch:
  pull_request:
    path:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/go.yml"
  push:
    branches:
      - master
    paths:
      - "**.go"
      - "**/go.mod"
      - "**/go.sum"
      - ".github/workflows/go.yml"

jobs:
  batch-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: batch_workflow/go.mod
          cache: true
          cache-dependency-path: batch_workflow/go.sum
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: batch_workflow
          skip-pkg-cache: true
  batch-test:
    needs: [batch-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: batch_workflow/go.mod
          cache: true
          cache-dependency-path: batch_workflow/go.sum
      - name: go tests
        run: go test ./...
        working-directory: ./batch_workflow
  invoice-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: tools/invoice/go.mod
          cache: true
          cache-dependency-path: tools/invoice/go.sum
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: tools/invoice
          skip-pkg-cache: true
  invoice-test:
    needs: [invoice-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: tools/invoice/go.mod
          cache: true
          cache-dependency-path: tools/invoice/go.sum
      - name: go tests
        run: go test ./...
        working-directory: tools/invoice
