name: invoice_searcher

on:
  workflow_dispatch:
  pull_request:
    path:
      - "tools/invoice/**.go"
      - "tools/invoice/**/go.mod"
      - "tools/invoice/**/go.sum"
      - ".github/workflows/invoice_searcher.yml"
  push:
    branches:
      - master
    paths:
      - "tools/invoice/**.go"
      - "tools/invoice/**/go.mod"
      - "tools/invoice/**/go.sum"
      - ".github/workflows/invoice_searcher.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: tools/invoice/go.mod
          cache: true
          cache-dependency-path: tools/invoice/go.sum
      - uses: golangci/golangci-lint-action@v3
        with:
          working-directory: tools/invoice
          skip-pkg-cache: true
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: tools/invoice/go.mod
          cache: true
          cache-dependency-path: tools/invoice/go.sum
      - name: go tests
        run: go test ./...
        working-directory: tools/invoice

